### ISSUE TITLE
luajit test.lua .. getting 2 failed tests

### ISSUE THREAD

**Issue by crberry50** [moonjit/moonjit#102]
I'm new to this, but ran this test after installation.  I'm running on POWER9.  Looked like a clean make and make install... 
$ uname -a
Linux p1237-met1 4.14.0-115.6.1.el7a.ppc64le #1 SMP Thu Mar 14 12:44:38 GMT 2019 ppc64le ppc64le ppc64le GNU/Linux

cat /etc/centos-release
CentOS Linux release 7.6.1810 (AltArch)

458 tests passed, but these two tests failed as below:

[319/460] lib/ffi/ffi_jit_call.lua --- ffi-jit-call
lib/ffi/ffi_jit_call.lua:44: assertion failed!
stack traceback:
	[C]: in function 'assert'
	lib/ffi/ffi_jit_call.lua:44: in function <lib/ffi/ffi_jit_call.lua:2>
	[C]: in function 'xpcall'
	test.lua:378: in function 'execute_plan'
	test.lua:413: in main chunk
	[C]: at 0x10006180

[414/460] unportable/math_special.lua --- math functions
unportable/math_special.lua:44: got: "+0 +0 +0 -1 +1 -1 +inf -inf nan"
expected: "+0 -0 +0 -1 +1 -1 +inf -inf nan"
stack traceback:
	[C]: in function 'error'
	unportable/math_special.lua:17: in function 'check'
	unportable/math_special.lua:44: in function <unportable/math_special.lua:42>
	[C]: in function 'xpcall'
	test.lua:378: in function 'execute_plan'
	test.lua:413: in main chunk
	[C]: at 0x10006180

**Comment by siddhesh** [comment]
The second failure was reported in #40, the first failure is new and is a newly enabled test. @seth-priya can you please check this out?

**Comment by seth-priya** [comment]
@siddhesh sure, will have a look

**Comment by seth-priya** [comment]
ok, so the first one out there [319/460] lib/ffi/ffi_jit_call.lua --- ffi-jit-call still passes for me on RHEL 7.6, but I am using a Power 8 (vs a Power 9 mentioned above), not sure if that could be the issue, will try to get access to a P9 and retry to replicate

**Comment by amitsadaphule** [comment]
The first issue _[319/460] lib/ffi/ffi_jit_call.lua --- ffi-jit-call_ is not reproducible either on Power 8 or on Power 9 for us. We tried on both ppc64le architectures (P8 and P9) with RHEL 7.6 as well as CentOS Linux release 7.6.1810 (AltArch).

**Comment by seth-priya** [comment]
@crberry50 based on comments from @amitsadaphule can you please confirm that this is still an issue for you?
