### ISSUE TITLE
Dose moonjit have a plan to support interge in the range [-2^64, 2^64]?

### ISSUE THREAD

**Issue by csbinghu** [moonjit/moonjit#104]
Dose moonjit have a plan to support interge data type in the range in the range [-2^64, 2^64]?

Because, date time is out of the range [-2^53, 2^53], and this will be a problem.

**Comment by siddhesh** [comment]
There is a wish, yes, but not a plan :)  We want to get it up to 5.3 at least, which means getting the full integer range.  I don't have the bandwidth to do it right now though, so I'm happy to accept patches.

**Comment by siddhesh** [comment]
See also: #63
