### ISSUE TITLE
Lua 5.3 implementation of __eq

### ISSUE THREAD

**Issue by mrmiller** [moonjit/moonjit#112]
I've got an implementation of 5.3's rules for the `__eq` metamethod. In short, it allows comparison between tables or userdata even if they have different metatables. Is this something that I should submit a pull request for?

From the Lua 5.1 docs:
```
"eq": the == operation. The function getcomphandler defines how Lua chooses a metamethod for comparison operators. A metamethod only is selected when both objects being compared have the same type and the same metamethod for the selected operation.

     function getcomphandler (op1, op2, event)
       if type(op1) ~= type(op2) then return nil end
       local mm1 = metatable(op1)[event]
       local mm2 = metatable(op2)[event]
       if mm1 == mm2 then return mm1 else return nil end
     end
```

And the Lua 5.3 docs:

`__eq: the equal (==) operation. Behavior similar to the addition operation, except that Lua will try a metamethod only when the values being compared are either both tables or both full userdata and they are not primitively equal. The result of the call is always converted to a boolean.`

**Comment by siddhesh** [comment]
That would be great.  Moonjit 2.2 and later aims at being compatible with newer lua so this behaviour change is acceptable on the master branch.
