### ISSUE TITLE
s390x JIT support for Moonjit 

### ISSUE THREAD

**Issue by Hyperion101010** [moonjit/moonjit#116]
Hi there, Shivam here
I applied for openmainframe mentorship a while back which had this project as one of the idea available for completion. Fast forward the results are out and unfortunately I am not selected for same.
Nonetheless, the project is very interesting and I would like to work on same.
I have co-ordinated with @siddhesh who shall mentor me for this work. According to the application draft the timetable and impl details [sit here](https://docs.google.com/document/d/1pPj4mYpZkT7_EbpG5zqVJBYeB4SeazRnAkPC4lDh0rg/edit?usp=sharing). 
As per the timetable, I am starting to work today. If you have any doubt/query about the impl details in the proposal doc please let me know.
This issue will be kind of index for all the upcoming PR's related to the work on the jit assembler.

PS: Sorry I didn't mail you early had some work on my end. 
For now working on "I'd suggest getting started with setting up a CI instance for
s390x on github using azure pipelines"

**Comment by Hyperion101010** [comment]
I did tried to setup my azure CI, here is what it looks like. 
I haven't done this before and looks like s390x arch isn't present on my moonjit CI.
Will @siddhesh or admin confirm this is correct. Pasting pics of the setup.

![Screenshot from 2020-05-03 14-29-13](https://user-images.githubusercontent.com/32175777/80910088-ccb91780-8d4a-11ea-8c07-51b9278cefbf.png)

Let me know.

**Comment by siddhesh** [comment]
Thank you for taking interest in this @Hyperion101010 . To begin with, please move the Project Plan section of your google doc proposal into the wiki here and make a link to it on the wiki home page.  I have opened up wiki editing so you should be able to do it yourself.

You'll need access to an S390x system to write and test your code.  Email me with a request for an account and I'll get you one; please include your ssh public key in your request.

We do not have an S390x CI yet.  That would be the ideal first step since the earlier CI on ci.linaro.org has been removed and we need an easy way for PRs to be tested on the right targets when they're posted here.  Right now CI is limited to x86_64 on Linux and Windows.

**Comment by Hyperion101010** [comment]
The wiki is updated [here](https://github.com/moonjit/moonjit/wiki). Should I add the calender/schedule?
Will mail you my details in a short while.

**Comment by grooverdan** [comment]
https://docs.travis-ci.com/user/multi-cpu-architectures/ is probably an easy way to get s390x (and arm64, ppc64le et) going on real hardware without playing with agents or github api tokens too much.

**Comment by siddhesh** [comment]
Agreed, I'm not opposed to adding travis support to moonjit in addition to the existing azure pipelines.

**Comment by Hyperion101010** [comment]
@siddhesh sent you my creds for the account process.

**Comment by Hyperion101010** [comment]
Thanks @siddhesh  worked like a charm. What should be my starting work? Any suggestions.

**Comment by grooverdan** [comment]
when I run a `make check` I get two s390x errors
<pre>
lib/ffi/ffi_enum.lua:68: too many callbacks
stack traceback:
	[C]: in function 'cast'
	lib/ffi/ffi_enum.lua:68: in function <lib/ffi/ffi_enum.lua:67>
	[C]: in function 'xpcall'
	test.lua:378: in function 'execute_plan'
	test.lua:413: in main chunk
	[C]: at 0x80005a28
</pre>

and:

<pre>
[438/488] unportable/ffi_arith_int64.lua --- unportable-test1
unportable/ffi_arith_int64.lua:50: test failed (got 1174526, expected 1174528) for:
+0 -0.5 +0.5 -1.5 +1.5 -1 +1 -2 +2 -37 +37 
0LL -1LL 1LL -2LL 2LL -37LL 37LL 
0LL -1LL 1LL -2LL 2LL -37LL 37LL 
0ULL 18446744073709551615ULL 1ULL 18446744073709551614ULL 2ULL 18446744073709551579ULL 37ULL

stack traceback:
	[C]: in function 'error'
	unportable/ffi_arith_int64.lua:17: in function 'cksum'
	unportable/ffi_arith_int64.lua:34: in function 'check'
	unportable/ffi_arith_int64.lua:50: in function <unportable/ffi_arith_int64.lua:5>
	[C]: in function 'xpcall'
	test.lua:378: in function 'execute_plan'
	test.lua:413: in main chunk
	[C]: at 0x80005a28
</pre>

I'm not sure of the importance of the precision of the second test however I suspect the first is more significant. Just my 2c worth.

**Comment by Hyperion101010** [comment]
Sorry for the delay had my online exams, will check it tommorow.

**Comment by Hyperion101010** [comment]
Yup I also see those failures on my s390 instance, logs pasted here https://pastebin.com/myy9uqek
Will look on the code for the test cases so will start checking from them. 
Thanks :)

**Comment by XVilka** [comment]
According to the schedule it's:
> August 1 - August 15: Start writing optimisation part for the assembler. Add support functions wherever necessary. Document the work. 
> August 15 - August 31: Test for the implementation and complete the remaining part of the assembler. 

Is there any available fork to try it?
