### ISSUE TITLE
MoonJIT - Identifying MoonJIT vs. others

### ISSUE THREAD

**Issue by ThePhD** [moonjit/moonjit#120]
I have a simple question based on an error someone else has received from working with the latest version of MoonJIT: https://github.com/ThePhD/sol2/issues/967#issuecomment-628290095

Is there a preprocessor-based way to define I am working with MoonJIT versus, say, vanilla LuaJIT? My personal preference would be a `#define MOONJIT_VERSION LUAJIT_VERSION` in the header for MoonJIT, so I can just check `#if defined (MOONJIT_VERSION)` or something similar.

If there is no simple way, I will get to work on some hackery; thanks for reading!

**Comment by siddhesh** [comment]
That's a reasonable request.  Done!
