### ISSUE TITLE
luaL_newstate() returns NULL on MacOS

### ISSUE THREAD

**Issue by Qix-** [moonjit/moonjit#121]
I just switched a fairly barebones projects from LuaJIT to MoonJIT and I'm seeing `NULL` returned from `luaL_newstate()`. Sending a debugger in, the underlying allocator uses `mmap()`, which is returning `EINVAL`, causing the overarching call to fail.

Further, `lua_newstate()` is stubbed out entirely, disallowing any sort of custom allocator to be used :/ This is a bit disappointing as my library gives the consumer the ability to specify an allocator. MoonJIT breaks this contract entirely.

**Comment by siddhesh** [comment]
Are you using 2.2.x or 2.1.x?  Can you please share a reproducer?  I don't remember any of us touching lua_newstate or luaL_newstate, so it's odd that you see a behaviour difference between luajit and moonjit.

**Comment by Qix-** [comment]
I'm using whatever is on master at the moment. I just wanted to throw it in and see if it worked.

`lua_newstate` gave me an error about 64-bit architectures requiring `luaL_newstate` for some reason (even though `luaL_newstate` is specified as being a wrapper around `lua_newstate` with a default allocator).

---

```c++
#include "./src/lua.hpp"

#include <cstdlib>

static void * l_alloc(void *ud, void *ptr, size_t osize, size_t nsize) {
	if (nsize == 0) {
		free(ptr);
		return NULL;
	} else {
		return realloc(ptr, nsize);
	}
 }

int main() {
	lua_newstate(&l_alloc, NULL);
	return 0;
}
```

Gives me:

```
Must use luaL_newstate() for 64 bit target
```

And then

```c++
#include "./src/lua.hpp"

#include <cstdlib>

int main() {
	return luaL_newstate() == NULL;
}
```

exits with status 1.

**Comment by siddhesh** [comment]
I had a bit of a peek into it (I don't have a Mac, sorry) and the only thing that has changed in the lua_newstate path that's different from LuaJIT is the string hash function selection.  However that should not directly result in lua_newstate returning NULL.

Re. lua_newstate being stubbed out; perhaps you're expecting GC64 to be the default.  That's not true for moonjit yet.  You still need `-DLUAJIT_ENABLE_GC64` to enable GC64.

**Comment by fsfod** [comment]
GC64 is on by default upstream did we skip that change or something?

**Comment by siddhesh** [comment]
Yeah I don't remember why I left it out.  It should be brought in.
