### ISSUE TITLE
error building for android on OSX

### ISSUE THREAD

**Issue by aleReimondo** [moonjit/moonjit#127]
Hi, I need to build moonjit for android in macOS Catalina (10.15.5) using NDK.
It goes to an error generating buildvm.o
The detail of my attempt to build follows.
Will appreciate any help or indication to success
----------------------------------------------------
export MACOSX_DEPLOYMENT_TARGET=10.5
NDKDIR=/Users/ale/Library/Android/sdk/ndk/21.3.6528147
NDKBIN=$NDKDIR/toolchains/llvm/prebuilt/darwin-x86_64/bin
NDKCROSS=$NDKBIN/aarch64-linux-android-
NDKCC=$NDKBIN/aarch64-linux-android21-clang
make CROSS=$NDKCROSS \
     STATIC_CC=$NDKCC DYNAMIC_CC="$NDKCC -fPIC" \
     TARGET_LD=$NDKCC

==== Building moonjit 2.3.0-dev ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
In file included from host/buildvm.c:75:
vm_arm64.dasc:1870:33: error: no member named 'J' in 'GG_State'
  dasm_put(Dst, 2506, GG_G2DISP+GG_DISP2J, (unsigned int)(LJ_GCVMASK), (unsigned int)((unsigned long long)(LJ_GCVMASK)>>32)...
                                ^~~~~~~~~
./lj_dispatch.h:113:20: note: expanded from macro 'GG_DISP2J'
#define GG_DISP2J       (GG_OFS(J) - GG_OFS(dispatch))
                         ^      ~
./lj_dispatch.h:103:29: note: expanded from macro 'GG_OFS'
#define GG_OFS(field)   ((int)offsetof(GG_State, field))
                              ^                  ~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/stddef.h:104:24: note: 
      expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~

**Comment by siddhesh** [comment]
`MACOSX_DEPLOYMENT_TARGET` needs to be `10.7` or newer.  I have documented this now based on https://github.com/LuaJIT/LuaJIT/issues/575#issuecomment-615895158.
