### ISSUE TITLE
Question about PPC64le support

### ISSUE THREAD

**Issue by elliottslaughter** [moonjit/moonjit#128]
Hi there,

Thanks for building/supporting Moonjit.

I had a question about your PPC64le support. According to the [installation instructions](https://github.com/moonjit/moonjit/blob/master/INSTALL.md) this platform is supported. I'm just wondering where this support came from? I ask because I've tried both of the existing LuaJIT forks for PPC64 and they're both horribly broken:

  * https://github.com/PPC64/LuaJIT, PR https://github.com/LuaJIT/LuaJIT/pull/54 (show-stopping bug here: https://github.com/PPC64/LuaJIT/issues/3)
  * https://github.com/mwkmwkmwk/LuaJIT, PR https://github.com/LuaJIT/LuaJIT/pull/140 (didn't bother posting a bug report on the second fork)

So, is the PPC64le support in this repo from one of those, or something else entirely? Is it feature complete (e.g., FFI)? Has it been tested?

I'd really like to use this but had so much pain with the last set of forks that I moved to PUC Lua for my immediate needs (though that's a hack, and I wouldn't mind being able to throw that work away).

**Comment by elliottslaughter** [comment]
So, just FYI, running `make && make check` on [Summit](https://www.olcf.ornl.gov/summit/) gave me 2 failing tests.

I guess based on the names these are not intended to be portable?

```
$ make check
==== Running tests for moonjit 2.3.0-dev ====
Creating ctest and cpptest
make -C test
make[1]: Entering directory `/autofs/nccs-svm1_home1/eslaught/summit/test_moonjit/test'
gcc -fPIC -Wall -Wextra -O2 -g  -I ../src -shared  -o clib/ctest.so src/ctest.c;
gcc  -fPIC -Wall -Wextra -O2 -g  -I ../src  -shared -o clib/cpptest.so src/cpptest.cpp;
make[1]: Leaving directory `/autofs/nccs-svm1_home1/eslaught/summit/test_moonjit/test'
performing checks
cd test && ../src/luajit test.lua
[  1/525] lang/andor.lua --- smoke
...
[475/525] unportable/ffi_arith_int64.lua --- unportable-test1
unportable/ffi_arith_int64.lua:50: test failed (got 1174526, expected 1174528) for:
+0 -0.5 +0.5 -1.5 +1.5 -1 +1 -2 +2 -37 +37 
0LL -1LL 1LL -2LL 2LL -37LL 37LL 
0LL -1LL 1LL -2LL 2LL -37LL 37LL 
0ULL 18446744073709551615ULL 1ULL 18446744073709551614ULL 2ULL 18446744073709551579ULL 37ULL

stack traceback:
	[C]: in function 'error'
	unportable/ffi_arith_int64.lua:17: in function 'cksum'
	unportable/ffi_arith_int64.lua:34: in function 'check'
	unportable/ffi_arith_int64.lua:50: in function <unportable/ffi_arith_int64.lua:5>
	[C]: in function 'xpcall'
	test.lua:379: in function 'execute_plan'
	test.lua:414: in main chunk
	[C]: at 0x10005730
...
[477/525] unportable/math_special.lua --- math functions
unportable/math_special.lua:44: got: "+0 +0 +0 -1 +1 -1 +inf -inf nan"
expected: "+0 -0 +0 -1 +1 -1 +inf -inf nan"
stack traceback:
	[C]: in function 'error'
	unportable/math_special.lua:17: in function 'check'
	unportable/math_special.lua:44: in function <unportable/math_special.lua:42>
	[C]: in function 'xpcall'
	test.lua:379: in function 'execute_plan'
	test.lua:414: in main chunk
	[C]: at 0x10005730
...
523 passed, 2 failed
to run just failing tests, pass command line arguments: 475 477
make: *** [check] Error 1
```

This is with GCC 6.4.0.

**Comment by elliottslaughter** [comment]
In case anyone is interested, I put together an initial patch to try out Moonjit in Terra. It's breaking with an error I don't entirely understand, see this thread for details: https://github.com/terralang/terra/pull/452

If any of the Moonjit maintainers have time to take a look and see if I'm doing anything obviously wrong, that would be appreciated.

**Comment by siddhesh** [comment]
The ppcle port is based on the luajit patchsets, but fixed up over time through bug reports and patches from various people  so while I won't claim that it's "well tested", it is definitely in better shape than the others.

The math_special test failure is known (#40).  The FFI test isn't but that may just be because the FFI test only just got enabled in the last weeks and was just not tested on ppc64le.  We only have x86_64 CI enabled at the moment.  Both test failures are ppc64le bugs.

> If any of the Moonjit maintainers have time to take a look and see if I'm doing anything obviously wrong, that would be appreciated.

That looks like it's unable to find the jit modules.  You need to set the `LUA_PATH` environment variable to point to the jit directory like so:

```
LUA_PATH=$PREFIX/usr/local/share/moonjit-2.3.0-dev/?.lua
```

**Comment by elliottslaughter** [comment]
Thanks, the `LUA_PATH` was able to fix the issue. Do you happen to know why this is occurring? We don't seem to see this with e.g. LuaJIT builds from the v2.1 branch.

I was able to get Terra to build with Moonjit on x86 and PPC64le, so I guess I'll try out some of my larger programs next and see if those work.

**Comment by siddhesh** [comment]
I don't know for sure, but I can give it a shot over the weekend if you can put in steps to reproduce.  AFAICT I haven't changed anything in the search/build paths.

**Comment by elliottslaughter** [comment]
```
git clone https://github.com/moonjit/moonjit.git
cd moonjit
make install PREFIX=$PWD/../install_moonjit CC=gcc CXX="gcc -fPIC" XCFLAGS=-DLUAJIT_ENABLE_GC64 MACOSX_DEPLOYMENT_TARGET=10.7
cd ..
touch empty.lua
install_moonjit/bin/moonjit-2.3.0-dev -bg empty.lua empty.bc
```

Should produce:

```
install_moonjit/bin/moonjit-2.3.0-dev: unknown luaJIT command or jit.* modules not installed
```

I don't think the exact Lua file you run it on matters, this is just a demonstration to make the point that it fails.

**Comment by elliottslaughter** [comment]
And if you compare this with the latest `v2.1` branch in https://github.com/LuaJIT/LuaJIT, you'll see that works:

```
git clone https://github.com/LuaJIT/LuaJIT.git
cd LuaJIT
make install PREFIX=$PWD/../install_luajit CC=gcc CXX="gcc -fPIC" XCFLAGS=-DLUAJIT_ENABLE_GC64 MACOSX_DEPLOYMENT_TARGET=10.7
cd ..
touch empty.lua
install_luajit/bin/luajit-2.1.0-beta3 -bg empty.lua empty.bc
```

(And in case you're wondering, I'm on macOS, but the same things happens on our Travis CI instance running Ubuntu 16.04.)

**Comment by siddhesh** [comment]
I've fixed this now.  Thanks for reporting it!
