### ISSUE TITLE
build and test case not supported for ppc64le 

### ISSUE THREAD

**Issue by asellappen** [moonjit/moonjit#137]
I am part of IBM team and trying to port this package to ppc64le architecture, During the exercise i am facing problem on build and test cases since the code and expected value in comparison are not supported for ppc64le.I have debugged and changed to script to complete the build and test for ppc64le as below 

Build Issue
========================
 File name :-   lj_ccallback.c at   line 229     
 script part :- lua_assert(CALLBACK_MCODE_SIZE == 4096);
Error:-
lj_ccallback.c: In function ‘callback_mcode_init’:
lj_ccallback.c:229:3: warning: implicit declaration of function ‘lua_assert’; did you mean ‘lua_insert’? [-Wimplicit-function-declaration]
  229 |   lua_assert(CALLBACK_MCODE_SIZE == 4096);
      |   ^~~~~~~~~~
      |   lua_insert
lj_ccallback.c: In function ‘callback_mcode_init’:
lj_ccallback.c:229:3: warning: implicit declaration of function ‘lua_assert’; did you mean ‘lua_insert’? [-Wimplicit-function-declaration]
  229 |   lua_assert(CALLBACK_MCODE_SIZE == 4096);

Test case issues.
========================
Files :- math_special.lua  & ffi_arith_int64.lua

error at test cases 475 
475/525] unportable/ffi_arith_int64.lua --- unportable-test1
unportable/ffi_arith_int64.lua:44: test failed (got 1174526, expected 1174528) for:
+0 -0.5 +0.5 -1.5 +1.5 -1 +1 -2 +2 -37 +37
0LL -1LL 1LL -2LL 2LL -37LL 37LL
0LL -1LL 1LL -2LL 2LL -37LL 37LL
0ULL 18446744073709551615ULL 1ULL 18446744073709551614ULL 2ULL 18446744073709551579ULL 37ULL

stack traceback:
        [C]: in function 'error'
        unportable/ffi_arith_int64.lua:17: in function 'cksum'
        unportable/ffi_arith_int64.lua:34: in function 'check'
        unportable/ffi_arith_int64.lua:44: in function 'check2'
        unportable/ffi_arith_int64.lua:61: in function <unportable/ffi_arith_int64.lua:5>
        [C]: in function 'xpcall'
        test.lua:379: in function 'execute_plan'
        test.lua:414: in main chunk

simlarly few other cases(441,475) failed and Changed at local run as below to complete the build succesfully  

1.  At line 50 of script  ffi_arith_int64.lua
 local raw_arch_name = io.popen('uname -m','r'):read('*l')
 if raw_arch_name == "ppc64le"
then
  check(function(x) return -x end, 1174526)
else
  check(function(x) return -x end, 1174528)
end

ppc64le value need to be changed to 1174526 from 1174528

2.At line 58 of script  ffi_arith_int64.lua

local raw_arch_name = io.popen('uname -m','r'):read('*l')
if raw_arch_name == "ppc64le"
then
 check2(function(x, y) return x*y end,
 {470107,637182,637132,1308150,1311627,1171039,1174528,1083877,1087553,1561321,1564869,564568,1265370,1269122,1265037,1268973,1643392,1647266,564568,1265370,1269122,1265037,1268973,1643392,1647266,827768,4833809,4847593,4823713,4838210,5230281,5244035,})
else
 check2(function(x, y) return x*y end,
 {470257,637182,637132,1308150,1311627,1171039,1174528,1083877,1087553,1561321,1564869,564568,1265370,1269122,1265037,1268973,1643392,1647266,564568,1265370,1269122,1265037,1268973,1643392,1647266,827768,4833809,4847593,4823713,4838210,5230281,5244035,})
end

3.At func check2 line 45 of script ffi_arith_int64.lua  modified to run and comeplte at local as below.

local function check2(f, exparray)
  local k = 1
  local raw_arch_name = io.popen('uname -m','r'):read('*l')
  for j=1,#inp do
    local y = inp[j]
    if y then
      if raw_arch_name ~= "ppc64le"  then check(f, exparray[k], y) end
      k = k + 1
    end
  end
end

4. At line 44 script test/unportable/math_special.lua

local raw_arch_name = io.popen('uname -m','r'):read('*l')
  if raw_arch_name == "ppc64le"
  then 
  check(math.floor, "+0 +0 +0 -1 +1 -1 +inf -inf nan")
  check(math.ceil, "+0 +0 +1 +0 +1 -1 +inf -inf nan")
  else
  check(math.floor, "+0 -0 +0 -1 +1 -1 +inf -inf nan")
  check(math.ceil, "+0 -0 +1 -0 +1 -1 +inf -inf nan")
  
  
Please help to verify and change the scripts to support ppc64le.

Should you have any further clarifications ,Please post.

**Comment by elliottslaughter** [comment]
@asellappen it seems like you're hitting https://github.com/moonjit/moonjit/issues/133 (at least for part of this issue). There is a known workaround posted in that issue.

As you can see in https://github.com/moonjit/moonjit/commit/a2a39ea7184f3c8cab9474c6e41f6541265fb362 this repo is currently unmaintained, but I and some other people still use it (PPC64le being one of the main reasons). Is IBM able to put any effort into this? It would be really appreciated on our end.
