### ISSUE TITLE
moonjit dead?

### ISSUE THREAD

**Issue by kallisti5** [moonjit/moonjit#140]
So... Just so I understand this.

* luajit/luajit - dead 3+ years
* moonjit/moonjit - dead 2 years
* openresty/luajit2 - alive

**Comment by alerque** [comment]
Did you mean [luajit/luakit](https://github.com/LuaJIT/LuaJIT/) dead 3+ **days**? There are lots issues in the Lua + JIT ecosystem, but just because a project doesn't have a release doesn't mean it's "dead".

**Comment by kallisti5** [comment]
oh.. ok.  So as a package maintainer... which version should I use?
I was looking here for the LuaJit age...   https://github.com/LuaJIT/LuaJIT/issues/563

Honestly, the luajit ecosystem is kind of a mess.   Is moonjit alive?   None of these are read-only so it's all a bit confusing :laughing:

**Comment by siddhesh** [comment]
moonjit is definitely quite dead; see the `About` in the project page.

**Comment by kallisti5** [comment]
ah.. ok.  Maybe make the repo read-only?  It's a toggle in the repo settings and will prevent issues + PR's, etc.

This situation is exactly why that toggle is there :-)
