### ISSUE TITLE
Would love having this in sync with standard Lua versions.

### ISSUE THREAD

**Issue by aryajur** [moonjit/moonjit#16]
Hi Siddhesh,
           Really appreciate your effort forking LuaJIT and trying to keep it moving. I started using Lua from 5.1 and LuaJIT was a big factor in deciding for it. Was tremendously disappointed when they decided not to be compatible with Lua 5.3. Would love if this goes in this direction. 
           But in any case keep it up. Thanks for your efforts.

Milind

**Comment by siddhesh** [comment]
I accepted some patches to get 5.3 support in, you can get them off the master branch.  I'm happy to accept patches to complete the 5.2 and 5.3 support (and 5.4 once it's stable) as long as they don't break ABI.

**Comment by aryajur** [comment]
Is there any special flag to enable 5.3 support?

**Comment by siddhesh** [comment]
They should be available by default.  Only 5.2 features that may break compatibility need the `-DLUAJIT_ENABLE_LUA52COMPAT` flag to enable them.

**Comment by siddhesh** [comment]
I just looked again at the commits Francois made; the only 5.3 change in so far is to change the signature of LuaL_len.  So it's still WIP.  I personally haven't worked on getting 5.3 support in, but I'm happy to accept patches.

**Comment by aryajur** [comment]
Ok thanks for letting me know. I would not be able to help in getting the
patches in since it is too far from what I can do in C.

**Comment by aryajur** [comment]
There is one fork of LuaJIT which is not maintained since 2017 but which integrated Lua 5.2 and Lua 5.3 native support: https://github.com/katlogic/ljx

**Comment by siddhesh** [comment]
I've created #71, #72 and #73 which should give more fine grained tracking of our progress with newer Lua support.
