### ISSUE TITLE
Makefile generates debug information by default

### ISSUE THREAD

**Issue by joe-92** [moonjit/moonjit#21]
Hi @siddhesh ,

first of all: thanks for maintaining this fork!

During compilation I noticed that the makefile [generates debug information by default](https://github.com/moonjit/moonjit/blob/4facef0644068cc0e096ff9a7ac293ec7d7d5221/src/Makefile#L59). That's probably not intended, right?

**Comment by siddhesh** [comment]
It was indeed unintentional, thanks for noticing!  Fixed in master and v2.1.

**Comment by joe-92** [comment]
Thanks for fixing! What do you generally think about switching to another build system, for example cmake, to unify the different makefiles?

**Comment by siddhesh** [comment]
This is a fairly simple project, so I don't see the value off the top of my head.  I am not wedded to that opinion though, so if a PR makes a persuasive case, I'm all for it.

**Comment by lblasc** [comment]
@joe-92 or even better to meson, see: https://github.com/franko/luajit

**Comment by siddhesh** [comment]
We can have a discussion on this in a separate issue because this one is already closed.  We need a persuasive use case (and patches of course!) to make changes to the build system.

**Comment by joe-92** [comment]
@siddhesh @lblasc I opened another issue, see #22
