### ISSUE TITLE
Support for riscv{32,64}

### ISSUE THREAD

**Issue by davidlt** [moonjit/moonjit#23]
It would be nice to see support for riscv32 and riscv64. riscv32 is still being upstreamed, but riscv64 has been stable for quite some time with various distributions available (Fedora, Debian, OpenSUSE, Gentoo, etc) with stable ABI. These should work on QEMU virt machine and SiFive Unleashed dev board.

**Comment by hippi777** [comment]
hi there! :)

im also interested in it as that seems to be the real pathway to hw/fw/sw freedom, as currently i think that all the other pathways to such/similar do bleed here and there, but note that im not enough deep in the details of these topics to say things for sure... but anyhow thats one of my very important aims that i wanna reach

so ive got the interest, ive got some good basics to approach it, but ive got no actual domain knowledge, but only general knowledge around the topic and kinda deep knowledge in computerscience, and also, im always in lack of time. if you (or any1 else) would like to approach it, then i will b around and try to catch up, so helping me in that with showing me the entrance of the rabbits hole, and offering me good docs & codes maybe can be profitable, but still, i cant promise anything with my lack of time, but my focus will be on the topic, even more as luajit, moonjit & co are just as well very important to me, and i wanna become able to handle all of its codes on my own by the time.

so yes, u can count me like that, and thx in advance for any help and effort! :)

bests! :)
