### ISSUE TITLE
Version naming is confusing

### ISSUE THREAD

**Issue by ufoul** [moonjit/moonjit#26]
Make it not annoying and use a version system innstead of what looks to be a random key

**Comment by siddhesh** [comment]
Can you please elaborate? What aspect of the version numbers or naming are you referring to?

**Comment by rubenwardy** [comment]
I suspect that they're getting commit hashes confused with versions

**Comment by joe-92** [comment]
Or they ment the previous releases which contained the date like "v2.1-20190221". I think this issue can probably be closed because of the new release process.

**Comment by siddhesh** [comment]
Ah OK, that makes sense.  I had accidentally pulled those in from openresty/luajit2 some months ago and they stuck.  Future version numbers will be coherent.  Closing since there's nothing to do but please reopen if you think we have misunderstood the issue.
