### ISSUE TITLE
 Any plans on implementing new GC?

### ISSUE THREAD

**Issue by DarkRoku12** [moonjit/moonjit#34]
Any plans on implementing this:
http://wiki.luajit.org/New-Garbage-Collector

Lua 5.4 implements a (new) generational GC, so i think a revamped GC would be a great feature.

**Comment by siddhesh** [comment]
Of the plans I've had, rewriting the GC wasn't one of them; I'm more interested in making sure that the current GC works better, for example without the 47-bit limitation.  It would be an interesting project though and if someone wants to do this in moonjit I'll be more than happy to provide a testing ground for 3.x.  There's definitely room for multiple GC implementations and possibly even runtime selection support.
