### ISSUE TITLE
ppc64le math.floor test case fails

### ISSUE THREAD

**Issue by siddhesh** [moonjit/moonjit#40]
math_special_test fails on ppc64le due to math.floor:

```
nportable/math_special.lua:44: got: "+0 +0 +0 -1 +1 -1 +inf -inf nan"
expected: "+0 -0 +0 -1 +1 -1 +inf -inf nan"
stack traceback:
	[C]: in function 'error'
	unportable/math_special.lua:17: in function 'check'
	unportable/math_special.lua:44: in function <unportable/math_special.lua:42>
	[C]: in function 'xpcall'
	test.lua:378: in function 'execute_plan'
	test.lua:413: in main chunk
	[C]: at 0x10005b00
```

**Comment by siddhesh** [comment]
cc @seth-priya

**Comment by walbon** [comment]
How I can execute it in a debug mode to check ?
(I'm newcomer in lua programing with some other skills to help).

**Comment by seth-priya** [comment]
Please refer to https://github.com/moonjit/moonjit/issues/2

**Comment by seth-priya** [comment]
@walbon have you had a chance to get to this one? else I can take a look, thanks!

**Comment by walbon** [comment]
@seth-priya Sorry, I was away from the work, allocated into another project.
So, I hadn't a chance to look.

**Comment by amitsadaphule** [comment]
While investigating the issue with the test failure at math_special.lua:44, I found that it is not specifically limited/related to math.floor/ceil handling. This is in fact, a generic failure in handling/representing -0 on ppc. I was able to reproduce the issue with luajit cli with the following expressions:
```
moonjit 2.2.0 -- Copyright (C) 2019-2020 moonjit developers. https://github.com/moonjit/moonjit
JIT: OFF
> =math.floor(-0)
0
> =math.ceil(-0)
0
> =-0
0
```
On x86, however, -0 is correctly returned as the result.

To simplify the debugging, I tried tracing the execution of "=-0" expression. The part of the code that deals with 0/-0 is in `bcemit_binop` in lj_parse.c (https://github.com/moonjit/moonjit/blob/2.2.0/src/lj_parse.c#L976 to https://github.com/moonjit/moonjit/blob/2.2.0/src/lj_parse.c#L980). Code snippet pasted below for reference:
```
    expr_toanyreg(fs, e);
  }
  expr_free(fs, e);
  e->u.s.info = bcemit_AD(fs, op, 0, e->u.s.info);
  e->k = VRELOCABLE;
```
On both ppc as well as x86, this part of the code gets executed. Specifically, the line `e->u.s.info = bcemit_AD(fs, op, 0, e->u.s.info);` inserts `lj_BC_UNM()` in the call hierarchy after `lj_BC_KSHORT()`. The sequence of execution while processing the expression is shown below, which is similar on x86 as well as ppc:
```
Breakpoint 1, lua_pcall (L=0x690b0378, nargs=0, nresults=-1, errfunc=1) at lj_api.c:1197
1197      status = lj_vm_pcall(L, api_call_base(L, nargs), nresults+1, ef);
(gdb) s
0x00000000100407dc in lj_vm_pcall ()
(gdb) s
Single stepping until exit from function lj_vm_pcall,
which has no line number information.
0x000000001004093c in lj_vm_call ()
(gdb) s
Single stepping until exit from function lj_vm_call,
which has no line number information.
0x00000000100409b4 in lj_vm_call_dispatch ()
(gdb) s
Single stepping until exit from function lj_vm_call_dispatch,
which has no line number information.
0x00000000100409c4 in lj_vm_call_dispatch_f ()
(gdb) s
Single stepping until exit from function lj_vm_call_dispatch_f,
which has no line number information.
0x00000000100402b4 in lj_BC_IFUNCV ()
(gdb) s
Single stepping until exit from function lj_BC_IFUNCV,
which has no line number information.
0x000000001003efc8 in lj_BC_KSHORT ()
(gdb) s
Single stepping until exit from function lj_BC_KSHORT,
which has no line number information.
0x000000001003e678 in lj_BC_UNM ()
(gdb) s
Single stepping until exit from function lj_BC_UNM,
which has no line number information.
0x000000001003ffa4 in lj_BC_RET1 ()
(gdb) s
Single stepping until exit from function lj_BC_RET1,
which has no line number information.
0x000000001003ff14 in lj_BC_RET ()
(gdb) s
Single stepping until exit from function lj_BC_RET,
which has no line number information.
0x0000000010040444 in lj_vm_return ()
(gdb) s
Single stepping until exit from function lj_vm_return,
which has no line number information.
0x000000001004054c in lj_vm_leave_unw ()
(gdb) s
Single stepping until exit from function lj_vm_leave_unw,
which has no line number information.
0x0000000010040494 in lj_vm_return ()
(gdb) s
Single stepping until exit from function lj_vm_return,
which has no line number information.
0x0000000010040498 in lj_vm_leave_cp ()
(gdb) s
Single stepping until exit from function lj_vm_leave_cp,
which has no line number information.
0x00000000100404a4 in lj_vm_leave_unw ()
(gdb) s
Single stepping until exit from function lj_vm_leave_unw,
which has no line number information.
lua_pcall (L=0x690b0378, nargs=0, nresults=-1, errfunc=1) at lj_api.c:1198
1198      if (status) hook_restore(g, oldh);
```
Here are the differences in operation on ppc and x86:
1. There is a difference in the way the `TValue` (https://github.com/moonjit/moonjit/blob/2.2.0/src/lj_obj.h#L172) object is populated on x86 and on ppc. If we take a snapshot specifically at this (https://github.com/moonjit/moonjit/blob/2.2.0/src/lj_parse.c#L976) point, we get the following representations on ppc and x86 resp:

**ppc**
```
(gdb) p e->u.nval
$2 = {u64 = 18446462594437873664, n = -nan(0xeffff00000000), {{gcr = {gcptr32 = 0}, i = 0}, it = 4294901759}, fr = {func = {gcptr32 = 0}, tp = {ftsz = -65537, pcr = {ptr32 = 4294901759}}}, u32 = {lo = 0, hi = 4294901759}}
```
Here i (int32 number) and it (i.e. int32 type) are populated. i=0 and it=LJ_TISNUM (0xFFFEFFFF).

**x86**
```
(gdb) p e->u.nval
$1 = {u64 = 0, n = 0, {{gcr = {gcptr32 = 0}, i = 0}, it = 0}, fr = {func = {gcptr32 = 0}, tp = {ftsz = 0, pcr = {ptr32 = 0}}}, u32 = {
    lo = 0, hi = 0}}
```
Here n (lua_number i.e. double) is populated. n = 0

So, ppc uses 32-bit integer for value, whereas x86 uses 64-bit double for value.

2. lj_BC_UNM gets executed before lj_BC_RET1 in both cases. It is supposed to insert the sign to complete -0 representation. On **ppc**, register **r14** points to the **base of the lua stack frame** (in memory) which contains the TValue to be operated upon and all the operations being performed are on the **32-bit** 0. However, on **x86** a **64-bit register xmm0** contains the value to be operated upon. Here are the respective register contents before and after lj_BC_UNM execution on ppc and x86:

**ppc**
```
0x000000001003e678 in lj_BC_UNM ()
(gdb) info reg r14
r14            0xb5980e10       3046641168
(gdb) p *0xb5980e10
$3 = 0
(gdb) p/x *0xb5980e14
$4 = 0xfffeffff
(gdb) s
Single stepping until exit from function lj_BC_UNM,
which has no line number information.
0x000000001003ffa4 in lj_BC_RET1 ()
(gdb) info reg r14
r14            0xb5980e10       3046641168
(gdb)  p *0xb5980e10
$5 = 0
(gdb)  p/x *0xb5980e14
$7 = 0xfffeffff
```
As you can see, there is no change post lj_BC_UNM here.

**x86**
```
0x000055555558a448 in lj_BC_UNM ()
(gdb) info reg $xmm0
xmm0           {v4_float = {0x0, 0x0, 0x2, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x68, 0xa9, 
    0x0, 0x40, 0x0, 0x0, 0x0, 0x0}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0xa968, 0x4000, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x4000a968, 0x0}, 
  v2_int64 = {0x0, 0x4000a968}, uint128 = 0x4000a9680000000000000000}
(gdb) p $xmm0
$1 = {v4_float = {0, 0, 2.01033974, 0}, v2_double = {0, 5.3052037438024692e-315}, v16_int8 = {0, 0, 0, 0, 0, 0, 0, 0, 104, -87, 0, 64, 0, 0, 
    0, 0}, v8_int16 = {0, 0, 0, 0, -22168, 16384, 0, 0}, v4_int32 = {0, 0, 1073785192, 0}, v2_int64 = {0, 1073785192}, 
  uint128 = 19807840626963073034220470272}
(gdb) s
Single stepping until exit from function lj_BC_UNM,
which has no line number information.
0x000055555558b467 in lj_BC_RET1 ()
(gdb) info reg $xmm0
xmm0           {v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x0, 0x0, 0x0, 
    0x0, 0x0, 0x0, 0x0, 0x0}, v8_int16 = {0x0, 0x0, 0x0, 0x8000, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x80000000, 0x0, 0x0}, v2_int64 = {
    0x8000000000000000, 0x0}, uint128 = 0x8000000000000000}
(gdb) p $xmm0
$2 = {v4_float = {0, -0, 0, 0}, v2_double = {-0, 0}, v16_int8 = {0, 0, 0, 0, 0, 0, 0, -128, 0, 0, 0, 0, 0, 0, 0, 0}, v8_int16 = {0, 0, 0, 
    -32768, 0, 0, 0, 0}, v4_int32 = {0, -2147483648, 0, 0}, v2_int64 = {-9223372036854775808, 0}, uint128 = 9223372036854775808}
```
Here we can see that the value changes to -0 post lj_BC_UNM.

We're trying to get more details on whether ppc is capable of supporting -0 representation with its' register set/instructions.

With these observations, I have the following questions:
1. Is -0 being interpreted as 0 really an issue w.r.t lua operations? Or could it be architecture dependent?
2. If answer to (1) is yes i.e. it's really a problem, what should be the way forward for fixing this issue?
	- Could this be an issue with the BC_UNM implementation in vm_ppc.dasc? What is this routine really expected to do in case of 0 (since 2's complement for 0 is 0 which definitely not useful)?
	- Does TValue usage on ppc need to be updated to use lua_Number (i.e. double) storage and the rest of the implementation (e.g. vm_ppc.dasc) need to be updated accordingly to operate on 64 bit value?

**Comment by siddhesh** [comment]
The failure to preserve sign is not an architecture limitation; it is because BC_UNM fails to preserve sign of the floating point zero.

**Comment by amitsadaphule** [comment]
Thanks @siddhesh for the feedback! I'll focus on debugging BC_UNM.

**Comment by amitsadaphule** [comment]
As per the code @ https://github.com/moonjit/moonjit/blob/2.2.0/src/lj_arch.h#L292, ppc is considered to be operating in LJ_NUMMODE_DUAL_SINGLE number mode (defaults to dual number mode), whereas x64 in LJ_NUMMODE_SINGLE_DUAL as per https://github.com/moonjit/moonjit/blob/2.2.0/src/lj_arch.h#L190. Found a few references of number modes w.r.t LuaJIT:
https://luajit.org/performance_ppc.html
http://wiki.luajit.org/architecture-support
https://news.ycombinator.com/item?id=2617754#:~:text=LuaJIT%2FARM%20uses%20the%20dual,are%20two%20different%20number%20types.

LuaJIT/moonjit code operates on numbers in different ways depending on this mode. On ppc, the value is parsed as an integer, whereas on x64 it is parsed as double. I tried to override the number mode used by ppc to non-DUALNUM by un-commenting https://github.com/moonjit/moonjit/blob/2.2.0/src/Makefile#L110 which gave correct result for the expression `=-0`. Also, I could verify, from the contents of address pointed to by r14, that the value was parsed and handled as double instead of integer with this change. However, when I tried to run tests with `make check`, it crashed and no tests were executed. I need to debug this further.

@siddhesh Is LJ_NUMMODE_DUAL_SINGLE the recommended mode for ppc64le?

**Comment by amitsadaphule** [comment]
Here is the analysis from one of my seniors who is Applications Specialist: Farid Parpia.

Please find the results of few expressions executed on ppc64le with moojit, Lua 5.1.4, Lua 5.3.4 below:
```
[root@dd026787fed1 moonjit]# ./src/luajit
moonjit 2.2.0 -- Copyright (C) 2019-2020 moonjit developers. https://github.com/moonjit/moonjit
JIT: OFF
> print(math.type(1.1))
float
> print(math.type(1.1-1.1))
integer
> print(math.type(math.pi))
float
> print(math.type(1.))
integer
> print(math.type(-0.))
integer
> print(-0.)
0
> print(-0)
0
>
```
```
[root@dd026787fed1 ~]# lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> print(math.type(1.1))
stdin:1: attempt to call field 'type' (a nil value)
stack traceback:
        stdin:1: in main chunk
        [C]: ?
> print(-0.)
-0
> print(-0)
-0
>
```
```
[parpia@p95a30 ~]$ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> print(math.type(1.1))
float
> print(math.type(1.1-1.1))
float                           <--- because the result is 0., which is a float
> print(math.type(math.pi))
float
> print(math.type(1.))
float
> print(math.type(-0.))
float                           <--- because the IEEE754 standard allows -0. as a valid floating-point number
> print(-0.)
-0.0
> print(-0)
0                               <--- because two's complement integers don't allow a -0, which, therefore, gets coerced to 0
> print(math.type(-0))
integer
> print(math.floor(-0))
0
> print(math.ceil(-0))
0
```

Here, Lua 5.1 fails to recognize `math.type` expression, which however is recognized by moonjit. Also, it appears that the split of the number type into integer and float first appeared in Lua 5.3. So, moonjit appears to be aiming for 5.3 compatibility by default. It is not clear that the test suite is correct, then, for the math.ceil and math.floor tests that began this thread, since the results for -0 in moonjit matches that in Lua 5.3.4.

But the behavior of moonjit apparently only accepting that something is a "float" if it has a nonzero decimal part still needs fixing.
```
> print(math.type(1.1))
float
> print(math.type(1.1-1.1))
integer
> print(math.type(1.))
integer
> print(math.type(-0.))
integer
> print(-0.)
0
```

@siddhesh please let us know your thoughts on this.
