### ISSUE TITLE
Build fails on ppc64le with clang compiler

### ISSUE THREAD

**Issue by SantoshMagdum** [moonjit/moonjit#55]
@siddhesh 

Build fails on ppc64le with clang compiler. 

**Build Steps -**
export JOBS=3
export LUAJIT_PREFIX=/opt/luajit21
export LUAJIT_SYSM_PREFIX=/opt/luajit21-sysm
export LUAJIT_COMMON_XCFLAGS="-DLUA_USE_APICHECK -DLUA_USE_ASSERT -DLUAJIT_NUMMODE=2 -O1"
export LUAJIT_XCFLAGS="-DLUAJIT_USE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT $LUAJIT_COMMON_XCFLAGS"
export LUA52=1
export CC=clang
export CC_FOR_BUILD=${CC_FOR_BUILD:-clang}
make clean
make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS="$LUAJIT_XCFLAGS" VERBOSE=1

**Build Errors -**

bash-4.2# make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS="$LUAJIT_XCFLAGS" VERBOSE=1
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
lj_arch.h:450:2: error: "Need at least GCC 4.3 or newer"
#error "Need at least GCC 4.3 or newer"
 ^
1 error generated.
lj_arch.h:450:2: error: "Need at least GCC 4.3 or newer"
#error "Need at least GCC 4.3 or newer"
 ^
1 error generated.
lj_arch.h:450:2: error: "Need at least GCC 4.3 or newer"
#error "Need at least GCC 4.3 or newer"

I have fix for these errors and I could compile with the clang.  I am looking more and checking the test cases,

Please share your views.

Also please suggest on below Valgrind errors on gcc builds. Did you get a chance to look at these errors?
           [Valgrind errors](https://github.com/openresty/luajit2/issues/83)

Thanks,
Santosh

**Comment by siddhesh** [comment]
That looks odd, what version of clang are you using?  Also, how did you fix the problem you saw?

Lets talk about valgrind in a separate issue and restrict this one only to clang.

**Comment by SantoshMagdum** [comment]
@siddhesh  I am using clang version 8.0.1.
I have raised a PR for changes I did to build with clang compiler - https://github.com/moonjit/moonjit/pull/67

Please have a look and suggest.
