### ISSUE TITLE
Apply to GitHub sponsorship

### ISSUE THREAD

**Issue by XVilka** [moonjit/moonjit#57]
The project might benefit from the sponsoring. I am sure there are many other projects and organizations who use LuaJIT and would be happy to chip in.

See [GitHub Matching Sponsorship](https://github.com/sponsors) program, when they match the contributions made through the [Sponsor](https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository) button:

![image](https://user-images.githubusercontent.com/203261/69779761-0c039b00-11e4-11ea-8aec-5399fab8d720.png)

Originally opened in the LuaJIT repo: https://github.com/LuaJIT/LuaJIT/issues/530

**Comment by siddhesh** [comment]
Thank you, that is a valuable suggestion.  I agree that monetary sponsorship is something that might give people more incentive to contribute, but at this moment I am unable to directly accept or manage sponsorship money.

I would encourage people to add bug bounties or similar in the meantime for people to pick up, or even contract engineers to do specific tasks in moonjit if they wish to monetarily support the project.  Hopefully some day we will be in a position to set up and directly manage a fund to sponsor people working on the project, either as GitHub sponsorships or through other means, but now is not the time for it.
