### ISSUE TITLE
Optional AOT caching ?

### ISSUE THREAD

**Issue by TSnake41** [moonjit/moonjit#61]
It could be an interesting feature (optional) to make AOT (Ahead-of-Time) caches for some branches.
It's especially useful in large code-bases that heavily depends on JIT (like simple algorithms).

Full AOT will be too hard for Lua, however, partial could be interesting.

**Comment by siddhesh** [comment]
It will need special annotations of some sort to identify code snippets to compile AOT, so it might go against JIT principles.  It's an interesting experiment though, so if you'd like to experiment with it and host its results, I'd be more than happy to review/accept it and put it behind a compile flag.

**Comment by fsfod** [comment]
The main problem with AOT is the JIT embeds lots of pointers to objects in code it emits.
