### ISSUE TITLE
make check fails on i686

### ISSUE THREAD

**Issue by siddhesh** [moonjit/moonjit#68]
The testsuite fails on i686:

```
[235/530] lib/string/lower_upper.lua --- smoke
[236/530] lib/string/lower_upper.lua --- repeatmake: *** [Makefile:156: check] Segmentation fault (core dumped)
```
AFAICT, the failures predate any major changes in moonjit, i.e. should be reproducible on luajit-2.1.0-beta3 as well, but I have not confirmed.  This needs a close look.

**Comment by joe-92** [comment]
Did you test this on "real" 32bit hardware? I can't reproduce this on an x86_64 CPU using the `-m32` GCC flag:
```
> ../src/luajit test.lua
[  1/523] lang/andor.lua --- smoke
[...]
[523/523] misc/debug.lua --- debug.* smoke tests
523 passed
> file ../src/luajit    
../src/luajit: ELF 32-bit LSB pie executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, [...], for GNU/Linux 3.2.0, stripped
```

**Comment by siddhesh** [comment]
Interesting, the source of this error is from the Fedora build I did yesterday:

https://kojipkgs.fedoraproject.org//work/tasks/6153/39456153/build.log

It may be due to the fortification flags that Fedora adds by default.

**Comment by joe-92** [comment]
I tried to reproduce this error on ArchLinux (with gcc 9.2.0), but all tests passed. This is the command line I used to build moonjit:

```
make amalg Q= E=@: PREFIX=/usr TARGET_STRIP=: 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now' MULTILIB=lib -j6
```
