### ISSUE TITLE
Add luaL_requiref function to the MoonJIT C API

### ISSUE THREAD

**Issue by izarif** [moonjit/moonjit#79]
I have a Lua module statically linked to the main application and this function would be useful. I think we can take implementation from here https://github.com/keplerproject/lua-compat-5.2/blob/c164c8f339b95451b572d6b4b4d11e944dc7169d/c-api/compat-5.2.c#L601

**Comment by siddhesh** [comment]
Tracked by #71

**Comment by siddhesh** [comment]
Fixed by #115
