### ISSUE TITLE
moonjit 2.2.0 broke string:trim()

### ISSUE THREAD

**Issue by MoNTE48** [moonjit/moonjit#86]
```
function string:trim()
	return (self:gsub("^%s*(.-)%s*$", "%1"))
end

assert(string.trim("\n \t\tfoo bar\t ") == "foo bar")
```

This causes a test failure with 2.2.0. But worked with 2.1.2.

**Comment by siddhesh** [comment]
This looks like the result of the patch to accept `\0` as a regular character in patterns, i.e. 7d6c156599d22556b90369f43e286ed658328e17

@fperrad, would you like to take a look at this?

**Comment by fperrad** [comment]
@siddhesh, at this time the return of `trim` is equal to the input value.

There is no match with the method `gsub`, but the method `match` works
```
moonjit 2.2.0 -- Copyright (C) 2019-2020 moonjit developers. https://github.com/moonjit/moonjit
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> s = "\n \t\tfoo bar\t "
> print(s:gsub('^%s*(.-)%s*$', '%1'))

 		foo bar	 	0
> print(s:match('^%s*(.-)%s*$'))
foo bar
> 
```
