### ISSUE TITLE
math_special test fails on armhf

### ISSUE THREAD

**Issue by siddhesh** [moonjit/moonjit#9]
math.floor in math_special test fails on armhf:

```
11:58:02 unportable/math_special.lua:44: got: "+0 +0 +0 -1 +1 -1 +inf -inf nan"
11:58:02 expected: "+0 -0 +0 -1 +1 -1 +inf -inf nan"
```

**Comment by siddhesh** [comment]
Same problem on ppc64le.

**Comment by ggardet** [comment]
@siddhesh any idea what the problem is here? 
openSUSE switched to moonjit, but armv6 and armv7 are failing due to this failing test.

**Comment by siddhesh** [comment]
I haven't looked at it closely enough due to limited bandwidth, but it may be a precision issue.  The testsuite doesn't have an xfail mechanism yet, otherwise I would have marked it as such since it's not a critical failure AFAICT.

**Comment by XVilka** [comment]
Since [v2.2.0 was released](https://github.com/moonjit/moonjit/releases/tag/2.2.0), maybe it makes sense to move this to [the v2.3 milestone](https://github.com/moonjit/moonjit/milestone/2)?
