### ISSUE TITLE
Need to create ctest.dll and cpptest.dll

### ISSUE THREAD

**Issue by girish946** [moonjit/moonjit#96]
We need to build `ctest.dll` and `cpptest.dll` for windows platform.
It needs to be created under `test/clib/` before executing `test.lua` from [windows.yml](https://github.com/moonjit/moonjit/blob/8b813fed4164bcdec5af3de6e5a5d3208479baf1/windows.yml#L13).

**Comment by fsfod** [comment]
This my bad attempt at a nmake file for windows to build them that seems to work

```
INTDIR=.\clib

CC=$(CC) /nologo
LINK=link /nologo /dll /NOIMPLIB ../src/lua51.lib
CCCOMMON=/c /Fo"$(INTDIR)\\" /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /DLUA_BUILD_AS_DLL /MD /EHsc /I"..\src"
CFLAGS=$(CFLAGS) /TC $(CCCOMMON)

all: clib/cpptest.dll clib/ctest.dll

{.\src}.c.obj:
  $(CC) $(CFLAGS) $<

{.\src}.cpp.obj:
  $(CC) $(CCCOMMON) $<
  
clib/ctest.dll: clib/ctest.obj
  $(LINK) -out:clib/ctest.dll $**

clib/cpptest.dll: clib/cpptest.obj
  $(LINK) -out:clib/cpptest.dll $**

clean:
	del clib\*.obj clib\*.dll clib\*.lib clib\*.exp
```

**Comment by girish946** [comment]
Thanks @fsfod 
Please send a PR.

**Comment by girish946** [comment]
Closing this issue now as the above Nmake code is there in `test/Makefile.win`.
