### ISSUE TITLE
not support for ppc64(big-endian)

### ISSUE THREAD

**Issue by piaoxuebingfeng** [moonjit/moonjit#97]
hi,
i was running moonjit on ppc64(big-endian),but it can not support JIT mode ,how can i do ?

$ ./luajit 
moonjit 2.2.0 -- Copyright (C) 2019-2020 moonjit developers. https://github.com/moonjit/moonjit
JIT: OFF
> os.exit()

$ ./luajit -j on
./luajit: no JIT compiler for this architecture (yet)

**Comment by siddhesh** [comment]
The way to support JIT for ppc64 BE (or LE for that matter) is to write a JIT compiler for it.  I'm afraid nobody has written one yet and as far as BE is concerned, it appears to me that there's little to no interest in developing for it.
